pipeline:
  install:
    image: node:lts-alpine3.15
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  testing:
    image: node:lts-alpine3.15
    group: testing
    commands:
      - yarn run test
      - sleep 5

  lint:
    image: node:lts-alpine3.15
    group: testing
    commands:
      - yarn run lint
      - sleep 5
